dataset_type: "AirSim" # AirSim or Gimbal

# infer_dataset:
  # - "/home/strage/gimbal_attitude_image/100hz/known_env/test_image/dji_rs3pro_20221118_145457/"
  # - "/home/strage/gimbal_attitude_image/100hz/known_env/test_image/dji_rs3pro_20221118_145840/"
  # - "/home/strage/gimbal_attitude_image/100hz/known_env/test_image/dji_rs3pro_20221118_150138/"

infer_dataset:
  - "/home/strage/flight_airsim_image/sequence8"

csv_name: "data_list.csv"

weights_top_directory: "/home/strage/integrated_attitude_estimator_log/ResNet/train_log_resnet50_pretrain_2022_12_08/train_log/"
weights_file_name: "weights.pth"

infer_log_top_directory: "/home/strage/integrated_attitude_estimator_log/ResNet/train_log_resnet50_pretrain_2022_12_08/inference_test_log/"
infer_log_file_name: "frame_infer_relust.csv"

yaml_name: "infer_config.yaml"

index_dict_name: "index_dict_-30_30_range_step1deg.csv"

index_csv_path: "/home/ros_catkin_ws/src/integrated_attitude_estimator/index_dict/index_dict_-30_30_range_step1deg.csv"

hyperparameters:
  img_size: 224
  transform_params:
    do_domain_randomization: "eval" #train or eval
    resize: 224 # For ColorGitter
    brightness: 0.4
    contrast: 0.4
    saturation: 0.5
    hue: 0.25
    kernel_size: 5 # For Gaussian Blur
    sigma_min: 0.2
    sigma_max: 2.0
    equalize_p: 0.5 # For Random Equalize
    elastic_alpha: 25.0 # For ElasticTransform
  network_type: "SENet" # TimeSformer or SENet
  num_classes: 63
  num_frames: 8
  deg_threshold: 30
  batch_size: 640 # 220 in TimeSformer, 640 in ResNet50
  num_epochs: 50 #50 in pretrain, 100 in finetuning
  optimizer_name: "RAdam"
  lr: 1e-5
  alpha: 5e-4
  num_workers: 40
  save_step: 10
  mean_element: 0.5
  std_element: 0.5
  do_white_makeup: False
  do_white_makeup_from_back: False
  whiteup_frame: 0
  timesformer:
    patch_size: 16
    attention_type: 'divided_space_time'
    depth: 3 #num transforemer layers
    num_heads: 12
  senet:
    resnet_model: "resnet50" # 18 34 50 101 152